Add various new scripts, a config file etc.
Signed-off-by: Stefan <stefan.tauner@gmx.at>

diff --git a/build-flashrom b/build-flashrom
--- a/build-flashrom
+++ b/build-flashrom
@@ -1,79 +1,11 @@
-#!/bin/bash -x
+#!/bin/bash
 # TODO: Handle tarballs later.
 
 . buildbot.conf
+. common.sh
 
 # remembers the VMs that were already running
 declare -A vms_were_running
-
-# stores a mapping of vbox VM names and their IP addresses
-declare -A vbox_ips
-
-fill_vbox_ips() {
-	for ck in "${!compilers[@]}"; do
-		local vmname=${vbox_names[$ck]}
-		[ -z $vmname ] && continue
-		local hostonlyif=$(vboxmanage showvminfo ${vmname} --machinereadable | grep -oP '(?<=hostonlyadapter2=")[^"]+')
-		local vmip=$(VBoxManage list hostonlyifs | grep -ozP "(?s)Name: +${hostonlyif}.*?IPAddress:\N*" | grep -ozP "(?<=IPAddress:       )[0-9.]+")
-		vmip=${vmip%.1}.2
-		if ! valid_ip "$vmip" ; then
-			msg_err "Could not retrieve IP for $ck correctly (got $vmip)"
-		fi
-		vbox_ips["$ck"]=$vmip
-	done
-}
-
-# This code is based on one from Linux Journal June 26, 2008 
-valid_ip() {
-	local ip=$1
-
-	# Check the IP address under test to see if it matches the extended REGEX
-	regex="^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$"
-	if [[ ! $ip =~ $regex ]] ; then
-		return 1
-	fi
-	oifs=$IFS
-	IFS='.'
-	for num in $ip ; do
-		if [ $num -gt 255 ]; then
-			IFS=$oifs
-			return 1
-		fi
-	done
-	IFS=$oifs
-	return 0
-}
-
-# checks if parameter is an element in an array. invocation example: is_in "gcc" "${available_compilers[@]}"
-is_in () {
-	arr=$1
-	shift
-	for elem in "$@"; do
-		[[ "$elem" == "$arr" ]] && return 0;
-	done
-	return 1
-}
-
-# checks if parameter is a key in an associative array. invocation example: is_key_in "dos" "$(declare -p available_compilers)"
-is_key_in () {
-	key="$1"
-	eval "local -A arr="${2#*=} # deserialize and eliminate old name/assignment
-	test -n "${arr[$key]}"
-}
-
-# checks if parameter is element in an associative array and returns the key in the 3rd variable.
-# invocation example: get_key_from_name "i586-pc-msdosdjgpp-gcc" "$(declare -p available_compilers)" "ret_val"
-get_key_from_name () {
-	name="$1"
-	eval "local -A arr="${2#*=} # deserialize and eliminate old name/assignment
-	for key in "${!arr[@]}"; do
-		if [ "${arr["$key"]}" = "$name" ]; then
-			eval "$3="$key""
-			return 0
-		fi
-	done
-	return 1
-}
 
 show_help() {
 	echo "Usage:
@@ -97,19 +29,9 @@ Options
     -nc or --no-cleanup
         do not cleanup working directories
 
-    Possible compilers are: ${!available_compilers[@]}"
+    Possible compilers are:"
+	printf '\t\t%s\n' "${!available_compilers[@]}" | sort
 	exit 1
-}
-
-msg_err () {
-	echo "$@ Aborting." >&2
-	exit 1
-}
-
-check_arg () {
-	if [ $# -ne 2 -o -z "$2" ] || [[ "$2" == -* ]]; then
-		msg_err "Missing argument for $1."
-	fi
 }
 
 #default values
@@ -121,6 +43,7 @@ libs_base="/home/${vm_user}/cross-libs"
 declare -A compilers=()
 flashrom_opts=()
 priv=-1
+priv_def=0 # default privacy setting
 cleanup=1
 dryrun=0
 j=2 # default threads
@@ -149,10 +72,8 @@ do
 		key_var=
 		if is_key_in "$2" "$(declare -p available_compilers)" ; then
 			compilers["$2"]="${available_compilers["$2"]}"
-		elif get_key_from_name "$2" "$(declare -p available_compilers)" "key_var"; then
-			compilers["$key_var"]="$2"
 		else
-			msg_err "$2 is not in the list of available compilers (nor their aliases)"
+			msg_err "$2 is not in the list of available compiler (configurations)"
 		fi
 		shift 2;;
 	-p|--private)
@@ -182,13 +103,13 @@ do
 		msg_err "invalid option: $1"
 		;;
 	*)	# everything else are flashrom build parameters
-		flashrom_opts+=(" $1")
+		flashrom_opts+=("$1")
 		shift;;
 	esac;
 done
 
 if [ "$priv" -eq -1 ]; then
-	priv=1
+	priv=$priv_def
 fi
 
 if [ ! -d "${flashrom_source}" -o ! -e "${flashrom_source}/flashrom.c" ]; then
@@ -196,9 +117,7 @@ if [ ! -d "${flashrom_source}" -o ! -e "${flashrom_source}/flashrom.c" ]; then
 fi
 
 if [ "${#compilers[@]}" -eq 0 ]; then
-	# These are the default compilers.
-	# Native and cross-builds possible on the same host, and a native build with
-	# clang to check compatibility with non-gcc
+	# By default enable all available compilers.
 	for k in "${!available_compilers[@]}" ; do
 		compilers["$k"]="${available_compilers["$k"]}"
 	done
@@ -215,13 +134,11 @@ while [ -h "$script_path" ]; do # resolve $script_path until the file is no long
 done
 buildbot_dir="$( cd -P "$( dirname "$script_path" )" && pwd )"
 
-fill_vbox_ips
 
 echo "buildbot_dir=${buildbot_dir}"
 echo "flashrom_source=${flashrom_source}"
 echo "compilers=${!compilers[@]}"
 echo "flashrom_opts=${flashrom_opts[@]}"
-echo "vbox_ips=${vbox_ips[@]}"
 echo
 
 PATH="${buildbot_dir}:${PATH}"
@@ -253,8 +170,11 @@ else
 		ln -s -f -T "${resultbase}" "${www_root}/buildresults/latest-public-build"
 	fi
 	echo "Build was requested in \"${flashrom_source}\"" >>"${results_file}"
-	echo "for ${!compilers[@]}" >>"${results_file}"
-	echo "with arguments \"${flashrom_opts[@]}\"." >>"${results_file}"
+	echo "with arguments \"${flashrom_opts[@]}\" for ${#compilers[@]} compiler configurations:" >>"${results_file}"
+	for ck in $(echo "${!compilers[@]}" | tr " " "\n" | sort | tr "\n" " "); do
+		echo " - ${ck}" >>"${results_file}"
+	done
+	echo >>"${results_file}"
 fi
 
 # Parameter parsing and verification done.
@@ -316,7 +236,7 @@ stop_vbox_vm () {
 	else
 		echo "Saving ${vmname} VM state failed. Trying to shut it down instead..."
 	fi
-	ssh root@${vmip} ${vmhaltcmd}>/dev/null 2>&1
+	ssh root@${vmip} ${vmhaltcmd} >/dev/null 2>&1
 
 	while ping -c 1 ${vmip} >/dev/null 2>&1; do
 		if [ $(date +%s) -ge ${deadline} ]; then
@@ -347,15 +267,16 @@ stop_vbox_vm () {
 build_prepare () {
 	local ck="$1"
 	shift 1
-	local workdir="${workdir_base}/${resultbase}/${ck}"
 	
-	case "$build_type" in
+	case "${build_types[$ck]}" in
 		vbox)
 			start_vbox_vm "$ck" || return 1
-			tar czf - -C "${flashrom_source}" --format=ustar . | ssh ${vm_user}@${vbox_ips[$ck]} "mkdir -p ${vm_workdir}/${resultbase}; cd ${vm_workdir}/${resultbase}; tar xzf -"
+			local workdir="${vm_workdir}/${resultbase}"
+			cat "${workdir_base}/${resultbase}/source.tgz" | ssh ${vm_user}@${vbox_ips[$ck]} "mkdir -p ${workdir} && cd ${workdir} && tar xzf -" >/dev/null 2>&1
 			;;
 		*)
-			mkdir -p "${workdir}" && cp -a "${flashrom_source}/." "${workdir}"
+			local workdir="${workdir_base}/${resultbase}/${ck}"
+			mkdir -p "${workdir}" && tar xzf "${workdir_base}/${resultbase}/source.tgz" -C "${workdir}" >/dev/null 2>&1
 			;;
 	esac
 }
@@ -364,7 +285,7 @@ build_execute () {
 	local ck="$1"
 	shift 1
 	local workdir="${workdir_base}/${resultbase}/${ck}"
-	case "$build_type" in
+	case "${build_types[$ck]}" in
 		vbox)
 			ssh ${vm_user}@${vbox_ips[$ck]} "cd ${vm_workdir}/${resultbase} && $@"
 			;;
@@ -380,7 +301,7 @@ build_fetch () {
 	shift 2
 	local workdir="${workdir_base}/${resultbase}/${ck}"
 	for file in "$@"; do
-		case "$build_type" in
+		case "${build_types[$ck]}" in
 			vbox)
 				scp -p "${vm_user}@${vbox_ips[$ck]}:\"${vm_workdir}/${resultbase}/${file}\"" "$dest/"
 				;;
@@ -394,7 +315,7 @@ build_fetch () {
 build_destroy () {
 	local ck="$1"
 	shift 1
-	case "$build_type" in
+	case "${build_types[$ck]}" in
 		vbox)
 			test "$cleanup" -eq 1 && ssh ${vm_user}@${vbox_ips[$ck]} "rm -rf ${vm_workdir}/${resultbase}"
 			stop_vbox_vm "$ck"
@@ -406,30 +327,24 @@ build_destroy () {
 	esac
 }
 
-# set variable build_type to
-#	- vbox if the compiler is hosted in a virtual box vm
-#	- host if we can compile on the host machine (possibly with a cross compiler)
-get_build_type () {
-	if is_key_in "$1" "$(declare -p vbox_names)" ; then
-		build_type="vbox"
-	else
-		build_type="host"
-	fi
-}
+declare -A make_cmds
 
-get_make_cmd () {
+add_make_cmd () {
 	local ck=$1
-	case "$build_type" in
+	if [ -z "${build_types[$ck]}" ]; then
+		fill_build_types
+	fi
+	case "${build_types[$ck]}" in
 		vbox)
-			if ssh ${vm_user}@${vbox_ips[$ck]} "command -v gmake >/dev/null 2>&1" ; then
-				make_cmd=gmake
+			if ssh ${vm_user}@${vbox_ips[$ck]} "command -v gmake" >/dev/null 2>&1 ; then
+				make_cmds[$ck]=gmake
+				echo "${vbox_names[$ck]} is using gmake"
 			else
-				make_cmd=make
+				make_cmds[$ck]=make
 			fi
 			;;
 		*)
-			make_cmd=make
-			return 0
+			make_cmds[$ck]=make
 			;;
 	esac
 }
@@ -441,34 +356,64 @@ build_it () {
 	echo "Starting $ck ($cc) build of ${flashrom_source}"
 	if [ "$dryrun" -ne 1 ]; then
 		local outdir="$resultdir/$ck"
-		if is_key_in "$ck" "$(declare -p lib_dirs)" ; then
-			local lib_option=LIBS_BASE=${libs_base}/${lib_dirs[${ck}]}
-		fi
-		get_build_type "$ck"
-		get_make_cmd "$ck"
 		mkdir "$outdir" || cur_err=1
 		[ "$cur_err" -ne 1 ] && { build_prepare "$ck" || cur_err=1; }
-		[ "$cur_err" -ne 1 ] && { build_execute "$ck" "$make_cmd" CC="$cc" ${lib_option} ${flashrom_opts[@]} 2>&1 | tee -a "$outdir/buildlog.txt" ;[ ${PIPESTATUS[0]} -eq 0 ] || cur_err=1; }
-		[ "$cur_err" -ne 1 ] && build_fetch   "$ck" "$outdir/" flashrom.8 flashrom flashrom.exe util/ich_descriptors_tool/ich_descriptors_tool util/ich_descriptors_tool/ich_descriptors_tool.exe 2>/dev/null
-		[ "$cur_err" -ne 1 ] && [ "$cleanup" -eq 1 ] && { build_execute "$ck" "$make_cmd" distclean 2>&1 | tee -a "$outdir/buildlog.txt" ;[ ${PIPESTATUS[0]} -eq 0 ] || cur_err=1; }
+		add_make_cmd "$ck"
+		local exec_args=("$ck" "${make_cmds[$ck]}" CC="$cc")
+		if is_key_in "$ck" "$(declare -p lib_dirs)" ; then
+			exec_args+=("LIBS_BASE=${libs_base}/${lib_dirs[${ck}]}")
+		fi
+
+		printf "Executing for %s: %q %q" "$ck" "${make_cmds[$ck]}" CC="$cc" | tee -a "$outdir/buildlog.txt"
+		[ -z "${lib_option}" ] || printf " %q" "${lib_option}" | tee -a "$outdir/buildlog.txt"
+		for opt in "${flashrom_opts[@]}" ; do
+			printf " " | tee -a "$outdir/buildlog.txt"
+			printf "%q" "$opt" | tee -a "$outdir/buildlog.txt"
+			exec_args+=("$opt")
+		done
+		printf "\n" | tee -a "$outdir/buildlog.txt"
+		[ "$cur_err" -ne 1 ] && { build_execute "${exec_args[@]}" >> "$outdir/buildlog.txt" 2>&1 ;[ ${PIPESTATUS[0]} -eq 0 ] || cur_err=1; }
+		[ "$cur_err" -ne 1 ] && build_fetch "$ck" "$outdir/" flashrom.8 flashrom flashrom.exe util/ich_descriptors_tool/ich_descriptors_tool util/ich_descriptors_tool/ich_descriptors_tool.exe  >> "$outdir/buildlog.txt" 2>/dev/null
+		[ "$cur_err" -ne 1 ] && [ "$cleanup" -eq 1 ] && { build_execute "$ck" "${make_cmds[$ck]}" distclean >> "$outdir/buildlog.txt" 2>&1 ;[ ${PIPESTATUS[0]} -eq 0 ] || cur_err=1; }
 		build_destroy "$ck" || cur_err=1 # unconditionally clean up
 	fi
 	return $cur_err
 }
 
+# stores the build type for every selected compiler
+#	- vbox if the compiler is hosted in a virtual box vm
+#	- host if we can compile on the host machine (possibly with a cross compiler)
+declare -A build_types
+
+fill_build_types () {
+	for ck in "${!compilers[@]}"; do
+		local build_type
+		if is_key_in "$ck" "$(declare -p vbox_names)" ; then
+			build_type="vbox"
+		else
+			build_type="host"
+		fi
+		build_types["$ck"]=$build_type
+	done
+}
 
 main () {
 	local errors=0
 	local error_builds=()
 	local -A cc_pids=()
-	local make_cmd
-	get_make_cmd "make_cmd"
 
-	#############################################
-	# clean up first the local source directory #
-	#############################################
-	test "$dryrun" -eq 1 || "$make_cmd" -C "${flashrom_source}" ${flashrom_opts[@]} distclean 2>&1
+	################################################
+	# prepare local source and working directories #
+	################################################
+	test "$dryrun" -eq 1 || "make" -C "${flashrom_source}" ${flashrom_opts[@]} distclean >/dev/null 2>&1
+	mkdir -p "${workdir_base}/${resultbase}" >/dev/null 2>&1
+	tar czf "${workdir_base}/${resultbase}/source.tgz" -C "${flashrom_source}" --format=ustar . >/dev/null 2>&1
 
+	####################################
+	# prepare some local map variables #
+	####################################
+	fill_build_types
+	fill_vbox_ips
 	##########################################
 	# then schedule compile runs in parallel #
 	##########################################
@@ -504,15 +449,16 @@ main () {
 	# cleanup and result processing #
 	#################################
 	echo "Done (${errors} errors)!"
-	echo >>"${results_file}"
-	echo "${errors} errors" >>"${results_file}"
+	echo "${errors} error(s)" >>"${results_file}"
 	if [ $errors -ne 0 ]; then
 		echo "The following builds failed:" | tee -a "${results_file}"
-		for ck in "${error_builds[@]}"; do
+		local fails=$(echo "${error_builds[@]}" | tr " " "\n" | sort | tr "\n" " ")
+		for ck in $fails; do
 			echo "$ck (${compilers[$ck]})" | tee -a "${results_file}"
 		done
 	fi
 	test "$dryrun" -eq 1 || echo "Results in ${resultdir}"
+	test "$dryrun" -eq 1 || mv "${workdir_base}/${resultbase}/source.tgz" "${resultdir}"
 	test "$dryrun" -eq 1 || rmdir "${workdir_base}/${resultbase}/" 2>/dev/null # not created for VM-only builds
 	test "$priv" -eq 1 -o "$dryrun" -eq 1 || chmod go+rx "$resultdir"
 	exit $errors
