Print which and how mandy builds failed, and return this number

diff --git a/build-flashrom b/build-flashrom
--- a/build-flashrom
+++ b/build-flashrom
@@ -125,17 +125,33 @@ test $priv -eq 1 || echo -n $(basename ${resultdir}) >${buildbot}/public_html/bu
 echo ${flashrom_opts} >$resultdir/buildparams.txt
 cd "${flashrom_source}"
 
+errors=0
+error_builds=()
 for cc in "${compilers[@]}"; do
 	echo "Starting $cc build in $(pwd)"
 	mkdir "$resultdir/$cc"
 	# We are not interested in cleanup logs for the previous run.
 	gmake distclean >/dev/null 2>&1
+	cur_err=0
 	build-prepare "$newid" "$cc"
-	build-execute "$newid" "$cc" gmake distclean 2>&1 | tee "$resultdir/$cc/buildlog.txt"
-	build-execute "$newid" "$cc" gmake CC="$cc" ${flashrom_opts} 2>&1 | tee -a "$resultdir/$cc/buildlog.txt"
+	build-execute "$newid" "$cc" gmake distclean 2>&1 | tee "$resultdir/$cc/buildlog.txt" ;[ ${PIPESTATUS[0]} -eq 0 ] || cur_err=1
+	build-execute "$newid" "$cc" gmake CC="$cc" ${flashrom_opts} 2>&1 | tee -a "$resultdir/$cc/buildlog.txt" ;[ ${PIPESTATUS[0]} -eq 0 ] || cur_err=1
 	build-fetch "$newid" "$cc" "$resultdir/$cc/" flashrom flashrom.exe util/ich_descriptors_tool/ich_descriptors_tool util/ich_descriptors_tool/ich_descriptors_tool.exe 2>/dev/null
-	build-execute "$newid" "$cc" gmake distclean 2>&1 | tee -a "$resultdir/$cc/buildlog.txt"
+	build-execute "$newid" "$cc" gmake distclean 2>&1 | tee -a "$resultdir/$cc/buildlog.txt" ;[ ${PIPESTATUS[0]} -eq 0 ] || cur_err=1
 	build-destroy "$newid" "$cc"
+	if [ ${cur_err} -ne 0 ]; then
+		errors=$(($errors + 1))
+		echo "The build with $cc above failed."
+		error_builds+=("$cc")
+	fi
 done
-echo "Done! :)"
+echo "Done (${errors} errors)!"
+if [ $errors -ne 0 ]; then
+	echo "The following builds failed:"
+	for b in "${error_builds[@]}"; do
+		echo "$b"
+	done
+fi
+echo "Results in ${resultdir}"
 test $priv -eq 1 || chmod go+rx $resultdir
+exit $errors
